### PR TITLE
Enhancement/Fix: Update Localization

### PR DESCRIPTION
**Pull request by ipokkel**
Updated localization for this Add On.

This PR includes:

- Add Domain Path to the plugin header.
- Add Text Domain to the plugin header.
- Change text domain to `pmpro-member-directory`.
- Move and change load text domain function to primary plugin file
- Remove redundant `inlcudes` and single file, `localization.php`, inside this directory
- Add master language file, `/languages/pmpro-member-directory.pot`
- Rename French (France) language pack files.
- Sync and update French (France) language pack files.

### CODE REVIEW

**Comment by andrewlimaza** [comment]
@ipokkel thanks for this, could you please add date_i18n to the templates and the profile template "Search For:" string isn't encapsulated correctly, the text domain is wrong.

**Comment by ipokkel** [comment]
@andrewlimaza Thank you, updated the PR

**Comment by sc0ttkclark** [comment]
We'll need to refresh this and implement the newer i18n GitHub action.

**Review by sc0ttkclark — CHANGES_REQUESTED** [review]
Needs refresh and to implement GitHub action

**Comment by sc0ttkclark** [comment]
On refresh -- looks like this PR is already up to date, we'll just want to make sure there are no conflicts with other PRs touching a few of these areas. We'll want to bring over the translation generation part of this from https://github.com/strangerstudios/paid-memberships-pro/blob/dev/.github/workflows/generate-translations.yml

**Pull request merged**
